[vite] connecting...
[vite] connected.
Error signing in with email and password 
_FirebaseError {code: "auth/invalid-credential", customData: {…}, name: "FirebaseError"}
code: "auth/invalid-credential"
customData: Object
name: "FirebaseError"
message: "Firebase: Error (auth/invalid-credential)."
stack: "FirebaseError: Firebase: Error (auth/invalid-credential).↵ at createErrorInternal (https://d9ad5041-d1af-4f41-a09a-2cf9debfdfd9-00-1km8c6eanlivp.riker.replit.dev/@fs/home/runner/workspace/node_modules/.vite/deps/firebase_auth.js?v=2f4113b7:697:37)↵ at _fail (https://d9ad5041-d1af-4f41-a09a-2cf9debfdfd9-00-1km8c6eanlivp.riker.replit.dev/@fs/home/runner/workspace/node_modules/.vite/deps/firebase_auth.js?v=2f4113b7:662:9)↵ at _performFetchWithErrorHandling (https://d9ad5041-d1af-4f41-a09a-2cf9debfdfd9-00-1km8c6eanlivp.riker.replit.dev/@fs/home/runner/workspace/node_modules/.vite/deps/firebase_auth.js?v=2f4113b7:1132:9)↵ at async _performSignInRequest (https://d9ad5041-d1af-4f41-a09a-2cf9debfdfd9-00-1km8c6eanlivp.riker.replit.dev/@fs/home/runner/workspace/node_modules/.vite/deps/firebase_auth.js?v=2f4113b7:1143:26)↵ at async _signInWithCredential (https://d9ad5041-d1af-4f41-a09a-2cf9debfdfd9-00-1km8c6eanlivp.riker.replit.dev/@fs/home/runner/workspace/node_modules/.vite/deps/firebase_auth.js?v=2f4113b7:4628:20)↵ at async loginWithEmailAndPassword (https://d9ad5041-d1af-4f41-a09a-2cf9debfdfd9-00-1km8c6eanlivp.riker.replit.dev/src/lib/firebase.ts:16:28)↵ at async login (https://d9ad5041-d1af-4f41-a09a-2cf9debfdfd9-00-1km8c6eanlivp.riker.replit.dev/src/hooks/use-auth.tsx:57:28)↵ at async onSubmit (https://d9ad5041-d1af-4f41-a09a-2cf9debfdfd9-00-1km8c6eanlivp.riker.replit.dev/src/pages/login.tsx:78:23)↵ at async https://d9ad5041-d1af-4f41-a09a-2cf9debfdfd9-00-1km8c6eanlivp.riker.replit.dev/@fs/home/runner/workspace/node_modules/.vite/deps/chunk-4BFJKWC4.js?v=2f4113b7:1465:9"
get stack: ƒ ()
set stack: ƒ ()
[[Prototype]]: Object

Login failed: 
_FirebaseError {code: "auth/invalid-credential", customData: {…}, name: "FirebaseError"}
code: "auth/invalid-credential"
customData: Object
name: "FirebaseError"
message: "Firebase: Error (auth/invalid-credential)."
stack: "FirebaseError: Firebase: Error (auth/invalid-credential).↵ at createErrorInternal (https://d9ad5041-d1af-4f41-a09a-2cf9debfdfd9-00-1km8c6eanlivp.riker.replit.dev/@fs/home/runner/workspace/node_modules/.vite/deps/firebase_auth.js?v=2f4113b7:697:37)↵ at _fail (https://d9ad5041-d1af-4f41-a09a-2cf9debfdfd9-00-1km8c6eanlivp.riker.replit.dev/@fs/home/runner/workspace/node_modules/.vite/deps/firebase_auth.js?v=2f4113b7:662:9)↵ at _performFetchWithErrorHandling (https://d9ad5041-d1af-4f41-a09a-2cf9debfdfd9-00-1km8c6eanlivp.riker.replit.dev/@fs/home/runner/workspace/node_modules/.vite/deps/firebase_auth.js?v=2f4113b7:1132:9)↵ at async _performSignInRequest (https://d9ad5041-d1af-4f41-a09a-2cf9debfdfd9-00-1km8c6eanlivp.riker.replit.dev/@fs/home/runner/workspace/node_modules/.vite/deps/firebase_auth.js?v=2f4113b7:1143:26)↵ at async _signInWithCredential (https://d9ad5041-d1af-4f41-a09a-2cf9debfdfd9-00-1km8c6eanlivp.riker.replit.dev/@fs/home/runner/workspace/node_modules/.vite/deps/firebase_auth.js?v=2f4113b7:4628:20)↵ at async loginWithEmailAndPassword (https://d9ad5041-d1af-4f41-a09a-2cf9debfdfd9-00-1km8c6eanlivp.riker.replit.dev/src/lib/firebase.ts:16:28)↵ at async login (https://d9ad5041-d1af-4f41-a09a-2cf9debfdfd9-00-1km8c6eanlivp.riker.replit.dev/src/hooks/use-auth.tsx:57:28)↵ at async onSubmit (https://d9ad5041-d1af-4f41-a09a-2cf9debfdfd9-00-1km8c6eanlivp.riker.replit.dev/src/pages/login.tsx:78:23)↵ at async https://d9ad5041-d1af-4f41-a09a-2cf9debfdfd9-00-1km8c6eanlivp.riker.replit.dev/@fs/home/runner/workspace/node_modules/.vite/deps/chunk-4BFJKWC4.js?v=2f4113b7:1465:9"
get stack: ƒ ()
set stack: ƒ ()
[[Prototype]]: Object